### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by krishguptadev**
Adds santa hubber 2 (1 is by @avneesh0612 )

### CODE REVIEW

**Review by avneesh0612 — COMMENTED** [review]
image

Need to add this...

**Comment by krishguptadev** [comment]
> image
> 
> Need to add this...

hmm.

**Comment by avneesh0612** [comment]
created #40 for this!

**Comment by avneesh0612** [comment]
do we need this PR open anymore?

**Comment by krishguptadev** [comment]
this image is not added yet.

**Comment by avneesh0612** [comment]
but there are 2 PRs for the images, right? 🤔

**Comment by krishguptadev** [comment]
> but there are 2 PRs for the images, right? 🤔

This one is for my image 🙂

**Comment by avneesh0612** [comment]
Oh lol, sorry didn't see

**Comment by avneesh0612** [comment]
I thought of the wrong thing 🤣

**Review by eddiejaoude — APPROVED** [review]
Thank you

**Pull request merged**
