### PR TITLE
Removed repeating pictures

### LINKED ISSUE #60: [DOCS] Some images in the README file in the Branding repo keeps repeating
### Description

Some images in the README file in the Branding repo keeps repeating
- The first and third image in screenshot

### Screenshots

image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Soumya-Kushwaha**
Fixes #60 

## Proposed Changes

 -Removing the repeating images

## Screenshots
Earlier:

image

Now:
image

### CODE REVIEW

**Review by Bashamega — CHANGES_REQUESTED** [review]
Hello:)

There are still some duplicates. Please remove them

**Comment by eddiejaoude** [comment]
Oh i missed this notification, sorry @Soumya-Kushwaha 

@Bashamega the shirt/hoodie is different, so i don't think there are duplicate

**Review by eddiejaoude — APPROVED** [review]
Thank you 👍

**Comment by Soumya-Kushwaha** [comment]
Thanks @eddiejaoude for merging this one.

**Pull request merged**
