### PR TITLE
Added Banner art and gif

### LINKED ISSUE #17: Feat: New banner art
I made a banner similar to Siddharth's as you mentioned once. I'll put it here for now since I don't know where to add it.
Picture here(I made a GIF version too)
if you want to make or suggest some edits, hope you like it :)
Eddie jaoude

### PR DESCRIPTION
**Pull request by starlightknown**
Fixes #17 

## Proposed Changes

  - Banner art 
  - related gif
  -

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Thank you for adding these 👍 . Could the file names be made more descriptive, so it is easier to know what file is what?

**Comment by starlightknown** [comment]
> Thank you for adding these +1 . Could the file names be made more descriptive, so it is easier to know which file is which?

yep, correcting it.

**Comment by starlightknown** [comment]
removed the older one, had a little defect. Added new gif and png without text, one with text. Also putting the edit link in the issue was a bad idea 🤕

**Review by eddiejaoude — APPROVED** [review]
These are awesome! Thank you! ❤️

**Pull request merged**
