### PR TITLE
Added Eddie Hub Community Logo

### PR DESCRIPTION
**Pull request by ahammadshawki8**

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Thank you for this 👍 

Could you move the file to a folder called `community`, then we can get others to add theirs too. I know @Vyvy-vi has lots that could be added too.

Also could you rename the file from `EddieHub Logo by AS8.png` to `collaboration0-coding-chibi-banner.png`

**Comment by ahammadshawki8** [comment]
No problem ⚡

**Comment by Vyvy-vi** [comment]
@eddiejaoude I'll add mine soon:tm: :+1:

**Comment by ahammadshawki8** [comment]
Now, I think it is ready to take off 🚀

**Comment by ahammadshawki8** [comment]
Hey @eddiejaoude, I fixed the issues a long time ago. so you can merge this pr.

**Comment by Vyvy-vi** [comment]
I think it would be merged in due time 🤓 
Eddie has a ton of github notifications to go through and most of the maintainers are busy on other projects :)

**Comment by ahammadshawki8** [comment]
> I think it would be merged in due time 🤓
> Eddie has a ton of Github notifications to go through and most of the maintainers are busy on other projects :)

Understood Earlier 🙄

**Comment by eddiejaoude** [comment]
Sorry I have so many GitHub notifications, I am about 10 days behind now, slowly catching up 

Screenshot 2021-03-12 at 10 04 42

**Comment by eddiejaoude** [comment]
@ahammadshawki8 the file name has `0` in it, I don't think that is needed?

**Comment by ahammadshawki8** [comment]
> Also could you rename the file from `EddieHub Logo by AS8.png` to `collaboration0-coding-chibi-banner.png`

I just did what you've asked me to do. Do you want me to change the filename from `collaboration0-coding-chibi-banner.png` to `collaboration-coding-chibi-banner.png`?

**Comment by eddiejaoude** [comment]
@ahammadshawki8 yes sorry I missed the `0`, yes please remove and we can get this merged 👍

**Comment by ahammadshawki8** [comment]
> @ahammadshawki8 yes sorry I missed the `0`, yes please remove and we can get this merged 👍

Ok, no problem.
Done.

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍

**Pull request merged**
